#!/usr/bin/env bash

if [ -e "~/git-completion.bash" ]
then
  source ~/git-completion.bash
fi

if [ -e "~/git-prompt.sh" ]
then
  source ~/git-prompt.sh
fi

export GIT_PS1_SHOWDIRTYSTATE=1
export PS1='\[\033[32m\]\u@\h\[\033[00m\]:\[\033[36m\]\w\[\033[31m\]$(__git_ps1)\[\033[00m\]\$ '
export APP_DIR='/var/www/__PROJECT_NAME__'

cd ${APP_DIR}
